### ISSUE TITLE
[Feature]: useUnmountEffect

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toss/slash#109]
### **Package Scope**

- [x] Add to an existing package (@toss/react)
- [ ] New package

### **Overview**

Declaratively enable unmounting behavior by handing over the callback that you want to cause when the component is unmounted.

Usually, I want a specific function to work when component is unmounted, but it was inconvenient.

### **Describe the solution you'd like**

```typescript
function useUnmoundEffect<F extends (...args: any[]) => void>(callback: F) {
  const preservedCallback = usePreservedCallback(callback);

  useEffect(() => {
    return () => preservedCallback();
  }, [preservedCallback]);
}
```

**Comment by HoseungJang** [comment]
Thanks @ChanhyukPark-Tech .

Could you show us some example?

**Comment by ChanhyukPark-Tech** [comment]
I agree too much with the opinion that there are not many situations where there will be cleanup without effect!
The case that I need to use this hook is as follows

currnet [@toss/lottie: Lottie.tsx](https://github.com/toss/slash/blob/main/packages/react/lottie/src/Lottie.tsx) 177 line

```typescript
  useEffect(() => {
    if (!isVisible) {
      return;
    }

    if (!autoPlay) {
      return;
    }

    startAnimation();

    return () => {
      animationChain?.destroy();
    };
  }, [animationChain, autoPlay, isVisible, startAnimation]);
```

I think `animationChain` is
It doesn't seem to have much to do with autoPlay, isVisible, and startAnimation in the dependency array.
But I felt awkward being in the useEffect hook where they were connected.

If the `animationChain` should be destroyed when this Lottie.tsx component is unmounted,
```typescript
useUnmountEffect(() => animationChain?.destroy());
```
at the top of this file
I thought it would be better to write that!

I can also use `useUnmountEffect` if I need to execute the callback I received from the parent component when the child component is unmounted

thank you😃

**Comment by raon0211** [comment]
This is actually an anti-pattern since every effect and cleanup must match. (See https://beta.reactjs.org/learn/synchronizing-with-effects) So I think it is not appropriate for this hook to be merged into our libraries. For debounce and Lottie — I think they are incorrect code and might break in React 18 strict mode. So I think we should fix them.

**Comment by ChanhyukPark-Tech** [comment]
Thank you for your kind explanation!
If I am working on a code to use like that pattern in the future, I should think about changing the structure itself.
I learned a lot!
