### ISSUE TITLE
wrong conditional export for esm in some repo.

### ISSUE THREAD

**Issue by JHSeo-git** [toss/slash#12]
First, Thanks to release this repo 👍 

## Steps to Reproduce

1. I created sample react app using vite(using "type": "module" in package.json).
2. I installed `@toss/impression-area@1.0.0`.
3. added simple code with `<ImpressionArea>`
```jsx
import "./App.css";
import { ImpressionArea } from "@toss/impression-area";

function App() {
  return (
    <div className="App">
      <ImpressionArea onImpressionStart={() => console.log("start")}>
        <div className="DummyBox" />
      </ImpressionArea>
    </div>
  );
}

export default App;
```
4. and occured following issue.

## issue

cannot resolve modules

![image](https://user-images.githubusercontent.com/61136724/194702020-bc2abf18-dcfe-4e36-9cb7-66cc65da75d2.png)

and I found wrong esm export path in dependencies modules `package.json`

- wrong path: `./esm/index.js`
- real path : `./esm/index.mjs`

![image](https://user-images.githubusercontent.com/61136724/194702385-b377d22f-52d6-4de4-9798-9e418f64090a.png)
![image](https://user-images.githubusercontent.com/61136724/194702558-efde327f-baab-45fc-9424-fd1a833235be.png)

so, to avoid the error, I tried to something:

```diff
- "module": "./esm/index.js",
+ "module": "./esm/index.mjs", 

- "import": "./esm/index.js"
+ "import": "./esm/index.mjs"
```
- @toss/impression-area/package.json
- @toss/use-ref-effect/package.json
- @toss/use-ref-effect/node_modules/@toss/use-preserved-callback/package.json

after fixed, works well.

![image](https://user-images.githubusercontent.com/61136724/194702599-9f671354-064c-4e7a-8be7-8c5bd2e5a73c.png)

And lastly, I think it would be a good idea to check it all over again.

Once again, Really appreciate release this repo. 😄

**Comment by HoseungJang** [comment]
@JHSeo-git 오픈소스화 된지 얼마 지나지 않았는데 빠르게 이슈 발견해주셔서 감사합니다!

Vite의 내부적인 resolution 로직이 exports -> module/browser 순으로 읽는 것으로 보이는데요. ([코드](https://github.com/vitejs/vite/blob/7b4d6e827aaf4da1b9785f82313745884ac6ce22/packages/vite/src/node/plugins/resolve.ts#L882))

사실  package.json에서 `module` field와 `import` field는 package.json의 표준이 아닙니다. ([Node.js package.json 문서](https://nodejs.org/api/packages.html#nodejs-packagejson-field-definitions))
그리고 yarn은 사실 publishConfig에 `import` field는 명시하고 있지 않습니다. ([yarn publishConfig 문서](https://yarnpkg.com/configuration/manifest/#publishConfig))

그래서 이 문제가 근본적으로 해결되기 위해선 아래의 작업이 이루어져야 할 것 같은데,

- publishConfig에서 `module`, `import` field 지우기

혹시 직접 작업해서 PR로 올려주실 의향이 있으실까요?

**Comment by JHSeo-git** [comment]
답변 감사합니다!

말씀하신대로 package.json `import`, `module`은 표준 필드가 아닙니다만 rollup, esbuild와 같은 번들러가 resolve 할 때 사용할지도 모르는 복잡미묘한(?) 부분이 있긴 한 것 같습니다.

그리고 현재 rollup config에서 publishConfig.exports map 파일 경로로 번들링 파일을 생성하는데, ESM 경우 `[name].mjs`로 확장자를 명시하고 있습니다. ESM 파일 확장자를 `.js`로 선언한다고 하더라도 entry file을 정상적으로 처리할 수 있게끔 수정하는 것도 좋을 것 같습니다.

**Comment by HoseungJang** [comment]
@JHSeo-git rollup, esbuild 정도의 번들러 또는 플러그인이 비표준인 `import`, `module` 등을 지원할 수는 있으나, 비표준 필드가 없다고 해서 resolution이 동작하지 않는 경우는 없을 거라고 생각합니다. 비표준 지원 앞에는 항상 표준 지원이 무조건적으로 되어있으니까요. 그래서 상관 없을거라고 생각합니다.

그리고 `.js`로 선언하든 `.mjs`로 선언하든 resolution은 제대로 동작할 수 있지만, 실제로 해당 JavaScript 모듈을 evaluate하는 시점에서 문제가 발생할 가능성이 커집니다.
`@toss/impression-area` 같이 package.json의 type field가 "commonjs"인 경우, (type field가 없는 경우 기본값이 "commonjs"입니다) ESM JavaScript에 대한 확장자를 `.mjs`로 사용하는 것이 맞습니다. 그래야 해당 파일에 대해 ESM Module loader가 사용됩니다.
또는.. `./esm` 디렉토리 루트에 package.json을 하나 만들고, `type: "module"`로 설정하는 편법도 있으나, 좋은 방법은 아닌 듯 합니다.

위 내용에 대한 자세한 설명은 [CommonJS와 ESM에 모두 대응하는 라이브러리 개발하기: exports field](https://toss.tech/article/commonjs-esm-exports-field)라는 글을 참고하시면 도움이 되실 것 같아요!

**Comment by JHSeo-git** [comment]
@HoseungJang 자세한 설명과 안내 감사합니다! 최근에 본 글인데 작성자 분이셨군요! 많은 도움 되었습니다.
