### ISSUE TITLE
[BUG]: @toss/lottie stopOnExit not work

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toss/slash#120]
### **Package Scope** 

Package name: @toss/lottie

### **Describe the bug**

A props called `stopOnExit` is only received, and the corresponding processing is not taking place in the function at all.

### **Expected behavior**
It seems that the `stopOnExit` will disappear, or it will have to be implemented according to actual behavior.

### **To Reproduce** 

Even if you set this value, it will not actually be reflected.

### **Additional context** 

![image](https://user-images.githubusercontent.com/69495129/200176864-363fed88-09ea-4123-ab80-808eaec29fdf.png)

![image](https://user-images.githubusercontent.com/69495129/200176875-0864a57b-3d4c-4dad-8eea-6cdbd9d5beec.png)

but in docs `stopOnExit` is described like this
>// 애니메이션이 화면 바깥으로 나갔을 때 애니메이션 재생을 잠시 일시정지하는지 여부

**Comment by raon0211** [comment]
Yes, you are right. It is a legacy prop. We should remove this from the code and docs.

**Comment by ChanhyukPark-Tech** [comment]
Can I make PR for this issue ?😁

**Comment by raon0211** [comment]
Yes, of course!

**Comment by ChanhyukPark-Tech** [comment]
solved by #126
