### ISSUE TITLE
[BUG]: Current, Many packages after build can contain unnecessary **.test.d.ts.

### ISSUE THREAD

**Issue by manudeli** [toss/slash#160]
### **Package Scope** 

Package name: all

### **Describe the bug**

Currently, Many packages (for example, @toss/emotion-utils) after build can contain unnecessary **.test.d.ts in dist directory like below picture.
![image](https://user-images.githubusercontent.com/61593290/204789469-5a995946-97b0-4c87-b4ab-3780133bffee.png)

or if other case that don't contain **.test.d.ts, test.ts / test.tsx file, thery are excluded by tsconfig.json.
but, every contributors can encounter this error like below picture. (for example @toss/error-boundary)
![image](https://user-images.githubusercontent.com/61593290/204789308-8d1ac9cd-9599-4651-8483-80dbb8ad9fb0.png)

### **Expected behavior**

exclude `["**/jest.setup.ts", "**/*.test.*", "**/*.spec.*", "**/*.stories.*", "**/__storybook__/*"]` only for build.
include `["**/jest.setup.ts", "**/*.test.*", "**/*.spec.*", "**/*.stories.*", "**/__storybook__/*"]` during anyone developing.

### **Possible Solution** 

During adding test after this https://github.com/toss/slash/pull/157#issuecomment-1330982866 , I met this problem.
after using little time to solve this problem, first time, I thought there's no configuration to test dom. but it isn't. ;(

Just, It's about excluded test file by tsconfig.json like below.

```json
{
  "extends": "./tsconfig.json",
  "exclude": ["**/jest.setup.ts", "**/*.test.*", "**/*.spec.*", "**/*.stories.*", "**/__storybook__/*"]
}
```

so, I could solve this bug by [this solution](https://github.com/toss/slash/pull/157/commits/fa15a42c7ba7dca28dd6081d4ad6f9515bfe051e): I added Solution Details below

#### Solution Details
1. use tsc -p tsconfig.build.json. only when yarn build.
2. use tsconfig.json don't exclude `["**/jest.setup.ts", "**/*.test.*", "**/*.spec.*", "**/*.stories.*", "**/__storybook__/*"]`  when developing.

How about adopt this solution in every packages? or Is there other way to solve this problem?

**Comment by raon0211** [comment]
Yes, this is right. We should definitely add this to all packages.

**Comment by manudeli** [comment]
Only this issue in @toss/error-boundary have been resolved.
It's not resolved for all packages.
Could I reopen this issue? and can I make new Pull Request to adopt [solution that have been adopted on @toss/error-boundary](https://github.com/toss/slash/pull/157#issuecomment-1332875808)?
