### ISSUE TITLE
[Feature]: How about add `indexBy` function 

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toss/slash#162]
### **Package Scope**

- [x] Add to an existing package
- [ ] New package

Package name: @toss/utils

### **Overview**
A function that indexes an array of objects based on a specific key value. It is a function that makes the object a key and value pair , which makes the cost of find specific data in the future cheaper.

```tsx

const foo = [
  { id: 1, name: 'park', age: 23 },
  { id: 3, name: 'kim', age: 21 },
  { id: 5, name: 'lee', age: 24 },
];

// normal approach
const result = foo.find(item => item.name === "park") // Tour all items.
const result = foo.find(item => item.name === "kim") // Tour all items.
const result = foo.find(item => item.name === "lee") // Tour all items.

// new indexBy function

const indexedObj = indexBy(foo, "name") // Tour just one tiem
const result = indexedObj["kim"] // quick search
const result = indexedObj["lee"] // quick search
const result = indexedObj["park"] // quick search
```

If indexed, it is a performance-friendly situation because it can be found immediately without looking for values while traveling all list.
These functions are good for those situations when they can be found quickly and easily after a just one traveling.

### **Describe the solution you'd like**
```tsx
type ElementType<T extends unknown[]> = T[number];

const indexBy = <ArrayObjectType extends Array<Record<PropertyKey, unknown>>, IndexType extends keyof ElementType<ArrayObjectType>>(
  arrayObj:ArrayObjectType, key:IndexType
) => {

  return arrayObj.reduce((acc, obj) => {
    acc[obj[key]] = obj;
     return acc
     }, {} as any);
}
```

### **Additional context**

If the developer uses a key which have value that is other than a Property Key, it should be treated well.

**Comment by ChanhyukPark-Tech** [comment]
thank you !

Yes, I know it well.
However, when comparing any two algorithms, it is common to compare them with [Worst-case](https://courses.cs.vt.edu/~csonline/Algorithms/Lessons/WorstCaseComparison/index.html), and I'm comparing them based on that.
If the length of the array is n, then `Array.prototype.find()` always has the time complexity of O(n)
but `indexBy` always has the time complexity of O(1) when searching after O(n) only for the first time.

**Comment by HoseungJang** [comment]
I think we can just use `Map` or `Set`, not the new util.

```typescript
const foo = [
  { id: 1, name: 'park', age: 23 },
  { id: 3, name: 'kim', age: 21 },
  { id: 5, name: 'lee', age: 24 },
];
```

```typescript
const names = new Set(foo.map(({ name }) => name));

if (name.has('park')) {
  ...
}
```

```typescript
const fooByName = new Map(foo.map((e) => [e.name, e]));

const result = fooByName.get('park');
```

**Comment by HoseungJang** [comment]
And In common cases, I think it's cheeper than the approach of `indexBy` to use `Array.prototype.find()`. Your example can be improved like:

```typescript
const foo = [
  { id: 1, name: 'park', age: 23 },
  { id: 3, name: 'kim', age: 21 },
  { id: 5, name: 'lee', age: 24 },
];

// Tours one time and the best time complexity is O(1).
const result = foo.find(item => {
  return item.name === 'park' || item.name === 'kim';
});


// But in case of using `indexBy`, the best time complexity is always O(n).
const indexedObj = indexBy(foo, 'name'); // O(n)
const result = indexObj['park'] ?? indexObj['kim'];
```

**Comment by raon0211** [comment]
There is actually an identical utility function in @toss/utils, namely [createMapByKey](https://slash.page/libraries/common/utils/src/createmapbykey.i18n/).

**Comment by ChanhyukPark-Tech** [comment]
Thank you for a good example and kind explanation!
