### ISSUE TITLE
[Feature]: Why needed two RegExp in the get function?

### ISSUE THREAD

**Issue by leokang94** [toss/slash#163]
### **Package Scope**

- [X] Add to an existing package
- [ ] New package

Package name: @toss/utils

### **Overview**

current `get` function uses about two RegExp(`/[,[\]]+?/`, `/[,[\].]+?/`).

```ts
export const get = <T = any>(obj: Record<string, any>, path: string, defaultValue?: T): T => {
  // ...
  const result = travel(/[,[\]]+?/) || travel(/[,[\].]+?/);
  // ...
};
```

### **Describe the solution you'd like**

I think the second RegExp can sufficiently replace the first RegExp like below.
```ts
export const get = <T = any>(obj: Record<string, any>, path: string, defaultValue?: T): T => {
  // ...
  const result = travel(/[,[\].]+?/);
  // ...
};
```

### **Additional context**

If you need it because of another edge case that I don't know, could you let me know?

**Comment by raon0211** [comment]
Yes, I think we could definitely simplify the function implementation. Do you have some time to open a pull request?

**Comment by leokang94** [comment]
Of course, Thanks!
I created PR #164 😀
