### ISSUE TITLE
[Feature]: Support @tanstack/react-query v4

### ISSUE THREAD

**Issue by manudeli** [toss/slash#171]
### **Package Scope**

- [x] Add to an existing package

Package name: react-query

### **Overview**

Support @tanstack/react-query v4 please

**Comment by raon0211** [comment]
Yes, this is definitely what we should support; we are having problem with backward compatibility issues. Meanwhile, you can use `@tanstack/react-query` with `npm:` protocol if your package manager supports it:

```shell
yarn add react-query@npm:@tanstack/react-query@^4
```

**Comment by hahnlee** [comment]
What about `@tanstack/react-query` as optional peer dependency and provide 
```tsx
import { useSuspendedQuery } '@toss/react-query/tanstack'
```
It can prevent BC.

**Comment by manudeli** [comment]
> What about `@tanstack/react-query` as optional peer dependency and provide
> 
> ```tsx
> import { useSuspendedQuery } '@toss/react-query/tanstack'
> ```
> 
> It can prevent BC.

@raon0211 @hahnlee 
I saw v5 is almost ready in @tanstack/react-query. So how about below more concise methods?

```
const { useSuspendedQuery } from '@toss/react-query/v4'
```

```
const { useSuspendedQuery } from '@toss/react-query/v5'
```

**Comment by manudeli** [comment]
useSuspenseQuery, useSuspenseQueries, and useSuspenseInfiniteQuery were added as official APIs in @tanstack/react-query v5. Therefore, I close this issue.
