### ISSUE TITLE
[Feature]: Add isDefined

### ISSUE THREAD

**Issue by jyangca** [toss/slash#183]
### **Package Scope**
- [x] Add to an existing package (@toss/utils)
- [] New package

### **Overview**
It declaratively returns the defined value, and returns `false` if the value is not defined(`undefined, null`). The main function of `isDefined` is to track undefined value, and is also useful for declaratively filtering array whice elements are objects.
```typescript
itemList = [
    {id: 1, isValid: true},
    {isValid: false},
    {isValid: false},
    {id: 4, isValid: true},
  ]
  
itemList.map(item => item.id).filter(isDefined)
```

### **Describe the solution you'd like**
```typescript
function isDefined<T>(argument: T | undefined | null): argument is T {
  return argument !== undefined && argument !== null;
}
```

**Comment by raon0211** [comment]
We actually have this function in our library, namely `isNotNil`.

https://slash.page/libraries/common/utils/src/isnotnil.i18n/
