### ISSUE TITLE
[BUG]: @toss/use-overlay change inner state of `CreateOverlayElement`'s JSX.Element 

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toss/slash#222]
### **Package Scope**

Package name: @toss/use-overlay

### **Describe the bug**

If I use the `open` method in overlay to open overlay, the states used in the open method are remembered as the values at the time when the open method is called. 
Even if the state is newly updated, overlaied component do not know the newly updated state. I think it's a closure problem, can we solve it?

### **Expected behavior**

Allows the changed states outside of the overlaid component to be immediately reflected in the overlaid component.

### **To Reproduce**

you can play [this code sand box](https://codesandbox.io/s/jovial-river-10fi1x?file=/src/App.tsx)

```tsx
import { useOverlay } from "@toss/use-overlay";
import { Dispatch, PropsWithChildren, SetStateAction, useState } from "react";
import "./styles.css";

const Dialog = ({
  caution,
  children
}: PropsWithChildren<{ caution: string }>) => {
  return (
    <div
      style={{
        width: "400px",
        height: "400px",
        backgroundColor: "blue",
        borderRadius: "8px",
        color: "red",
        margin: "30px",
        padding: "30px"
      }}
    >
      {children}
      this is {caution} // this is not updated when click button
    </div>
  );
};

const CustomDialog = ({
  setCaution
}: {
  setCaution: Dispatch<SetStateAction<string>>;
}) => {
  return (
    <button onClick={() => setCaution(new Date().toString())}>
      CLICK TO CHANGE CAUTION
    </button>
  );
};

export default function App() {
  const [caution, setCaution] = useState<string>("");
  const overlay = useOverlay();

  const onClickHandler = () => {
    overlay.open(() => (
      <Dialog caution={caution}>
        <CustomDialog setCaution={setCaution} />
      </Dialog>
    ));
  };

  return (
    <>
      <button
        onClick={onClickHandler}
        style={{
          width: "200px",
          height: "80px",
          backgroundColor: "white",
          borderRadius: "4px"
        }}
      >
        OPEN MODAL
      </button>
    </>
  );
}

```

**Comment by ChanhyukPark-Tech** [comment]
I think it is related with javascript closure

**Comment by dengoyoon** [comment]
Is it correct that the issue proposed in the example code above does not immediately render the overlay area when the 'click to change caution' button is pressed?

https://github.com/toss/slash/blob/main/packages/react/use-overlay/src/OverlayProvider.tsx
Considering the internal code of `OverlayProvider`, the code you wrote can be thought of as follows
```
<OverlayContext.Provider>
  <App/>
  <React.Fragment> // Overlay
    <Dialog caution={**App's internal status(caution)**}>
      <CustomDialog setCaution={**App's internal set status(setCaution)**} />
    </Dialog>
  </React.Fragment>
</OverlayContext.Provider> 
```

Even if you change the status value of the `App` in Overlay's Component, only the `App` will be rerendered. 
The fact that the component that ran `setCaution` is not re-rendered is seen as the correct behavior of React

Therefore, the problem does not appear to be a bug, and I think it can be solved in the same way as global status management.

Am I right in understanding this question?

**Comment by ChanhyukPark-Tech** [comment]
@dengoyoon 
You're right.
I realized it when I saw your example.
Thank you for suggesting a good solution,😄 Global Status Management can solve this issue If I change the structure, I can solve it
Have a great day!
