### ISSUE TITLE
[Feature]:특정한 overlay만 열고 닫는 방법이 있을까요?

### ISSUE THREAD

**Issue by baesku789** [toss/slash#230]
### **Package Scope**

- [ ] Add to an existing package
- [ ] New package

Package name:

### **Describe the solution you'd like**

id값이 자동으로 생성되고 export되지 않아서 오버레이가 사용된 컴포넌트에서만 열고 닫을 수 있는 것 같은데
혹시 다른 컴포넌트에서 특정한 오버레이를 열고 다는 방법이 있을까요?

**Comment by ChanhyukPark-Tech** [comment]
Can't we use useOverlay to manage the returned object as a global state and refer it to other components?
