### ISSUE TITLE
[BUG]: typedStorage import type error

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toss/slash#243]
### **Package Scope**

Package name: @toss/storage

### **Describe the bug**

>TypedStorage is subpath exported module. You should use @toss/storage/typed to use it.

when I use that import statement type error occurs.
<img width="456" alt="image" src="https://github.com/toss/slash/assets/69495129/1c0ee757-ac95-40ad-87b2-3ccb8ef8ef9a">

because there is no typed file in node_modules
<img width="419" alt="image" src="https://github.com/toss/slash/assets/69495129/73a1fdbd-7482-440d-a891-1cebfea3fca6">

### **Expected behavior**

```tsx
import { TypedStorage } from "@toss/storage/typed"; // should not occur type error
```

### **To Reproduce**

I'm used classic yarn not yarn berry

[link](https://github.com/toppingskorea/mungther-survey/blob/main/src/apps/main/components/modals/SubmitModal.hooks.ts)

### **Possible Solution**

1. Using TypeScript paths option: Update the TypeScript configuration file (tsconfig.json) with the paths option to redirect module paths. By mapping @toss/storage/typed to @toss/storage/dist/typed, you can resolve the type error. Here's an example:

```tsx
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@toss/storage/typed": ["./node_modules/@toss/storage/dist/typed"]
    }
  }
}
```

but it is not good for DX
every project it should be considered

2. Directly move or copy files: Move or copy the contents of @toss/storage/typed to @toss/storage/dist/typed directly. By doing this, you can keep the import statement as it is without modifying it, and the type error should be resolved.

**Comment by HoseungJang** [comment]
This fixed in https://github.com/toss/slash/pull/251.

And it's helpful for you to see [how module resolution work in Node.js](https://nodejs.org/api/packages.html), or [this article,](https://toss.tech/article/commonjs-esm-exports-field).
