### ISSUE TITLE
[BUG] useQueryParam is not safe typely, runtimely

### ISSUE THREAD

**Issue by manudeli** [toss/slash#254]
related https://github.com/toss/slash/pull/241

> I have reviewed but I still think this change is not appropriate. Regardless of the intention of `useQueryParam`, someone may have already used it like:
> 
> ```ts
> const productIds = useQueryParam<string[]>('productIds');
> const parsedProductIds = productIds.map((id) => parseInt(id));
> ```
> 
> I understand that you want to contribute, but It would be better to keep the previous implementation.

Even in this case, there is an error when used with parser.
If url is `https://example.com?productIds=1&productIds=2`
```ts
const productIds = useQueryParam<string[]>('productIds', {
  parser: (productIds) => { // productIds will be ["1", "2"], but typely this is string... then, what role is parser?
    /* we can't use productIds.map((id) => parseInt(id)) */
  }
});
```
You can see example typely invalid example or runtimely invalid example
#### typely invalid (https://example.com?productIds=1&productIds=2)
![image](https://github.com/toss/slash/assets/61593290/550ae585-be45-4257-bf15-2372f98b19ce)
#### runtimely invalid (https://example.com?productIds=1&productIds=2)
![image](https://github.com/toss/slash/assets/61593290/b4f187b5-78fb-44da-b35f-9ee079780f09)

Even though there are clearly edge cases in the code, It is difficult to understand why Pull Requests or other code suggestion cannot be accepted only because it is a BREAKING CHANGE. So what is BREAKING CHANGE for and why do other libraries do major bumps? If necessary, I think we should proceed with a BREAKING CHANGE.

_Originally posted by @manudeli in https://github.com/toss/slash/issues/241#issuecomment-1585147140_

**Comment by manudeli** [comment]
If BREAKING CHANGE is difficult, creating an API with a new name, treating the API as deprecated, and gradually removing it seems like a way.

**Comment by HoseungJang** [comment]
https://github.com/toss/slash/pull/241#issuecomment-1585189795
