### ISSUE TITLE
[Feature]: update useBooleanState return value Array to Object

### ISSUE THREAD

**Issue by minsoo-web** [toss/slash#262]
### **Package Scope**

- [x] Add to an existing package
- [ ] New package

Package name: @toss/react

### **Overview**

I think is more convenient return value is Object not array

#### Situations

Array return value is up to user remember what position it is

```ts
// In this case developer stop coding, and check docs for 
// where is it (such as where is the value, and where is the toggle function)
const [] = useBooleanState()
```

---

Array return value is inconvenient for using specific return value

```ts
// developer who wants to taking boolean value and toggle function
const [bool, _, _, toggle] = useBooleanState()
```

### **Describe the solution you'd like**

I Propose change the return value array to Object value

for example (for user interface)

```ts
const { value, toggle } = useBooleanState()
```

[reference - @chakra-ui/useDisClosure](https://chakra-ui.com/docs/hooks/use-disclosure)

**Comment by ChanhyukPark-Tech** [comment]
I think it's a good direction from array to object.(cuz DX)
Considering the many services that are using this hook, how do we consider `sub-compatibility`? 
Will it be solved if we specify  just "BREAKING CHANGE"?

**Comment by minsoo-web** [comment]
Thank you for your opinion. @ChanhyukPark-Tech 

Thank you for pointing out what I was worried about, too. 
I think it could be a **fatal issue** for someone who is upgrading the version. (Because the return type is different)

However, I suggested this issue because I thought it would be an acceptable change considering the many people who _**will install this package latest version.**_

**Comment by manudeli** [comment]
@minsoo-web, You can check other maintainer's opinions in https://github.com/toss/slash/pull/203

**Comment by minsoo-web** [comment]
Thank you @manudeli !!
I understand about this Hook's history and check other maintainer's options.
This Issue can be closed because new API (useToggleState) is created #273.

So I close this Issue
