### ISSUE TITLE
[BUG]: useOutsideClickEffect does not behave like a document

### ISSUE THREAD

**Issue by sa02045** [toss/slash#293]
### **Package Scope**

Package name: @toss/react

### **Describe the bug**
useOutsideClickEffect does not behave like a document

[useOutsideClickEffect Document](https://github.com/toss/slash/blob/fe40c2942fd1b4ddbf1dc9b34dffdffa2b91ccae/packages/react/react/src/hooks/useOutsideClickEffect.ko.md)

Example 1

```js
const ref = useRef<HTMLElement>(null);

// doesn't work 
useOutsideClickEffect(ref, () => {
  console.log('outside clicked!');
});
```

<img width="400" alt="스크린샷 2023-07-20 오전 8 41 33" src="https://github.com/toss/slash/assets/50866506/7c548e39-f502-4ae6-8033-e6913a6d6dbd">

<img width="400" alt="스크린샷 2023-07-19 오후 10 45 54" src="https://github.com/toss/slash/assets/50866506/497f4727-6f6a-4c5d-b0e1-be95f7755ffe">

### **Expected behavior**

The useOutsideClickEffect function operates by receiving the return value RefObject of useRef

```js
const ref = useRef<HTMLElement>(null);

// work!
useOutsideClickEffect(ref, () => {
  console.log('outside clicked!');
});
```

### **To Reproduce**

"react": "^18.2.0",

Only the code generated by CRA, App.tsx, has been modified as follows

```js
import { useRef } from "react";
import { useOutsideClickEffect } from "@toss/react";

function App() {
  const ref = useRef<HTMLDivElement>(null);

  useOutsideClickEffect(ref, () => {
    console.log("hello");
  });

  return (
    <div className="App">
      <h1 ref={ref}>hello</h1>
    </div>
  );
}

export default App;

```
### **Possible Solution**

useOutsideClickEffect parameter 'container' should be as follows.

```js
AS-IS
useOutsideClickEffect(container: OneOrMore<HTMLElement | null>, callback: () => void)

TO-BE
useOutsideClickEffect(container: OneOrMore<React.RefObject<HTMLElement> | null>, callback: () => void)
```

**Comment by ChanhyukPark-Tech** [comment]
Thank you for the good issue.

**I think there is no problem with the interface and implementation**, but there is an error in the code written in the example of the document.

I think below example is common usage

```tsx
const [wrapperEl, setWrapperEl] = useState<HTMLDivElement | null>(null);

useOutsideClickEffect(wrapperEl, () => {
    onOutsideClick();
});

<Flex ref={setWrapperEl} >
      {children}
</Flex>

```

**Comment by sa02045** [comment]
https://codesandbox.io/s/zealous-edison-4p39xp?file=/src/App.js

It doesn't work as a result of operating with the changed code. Is there anything I'm missing?

I think the components that use this hook need to be re-rendered at least once since the initial rendering to work properly. (State update , Side Effect , whatever..) 

This hook does not appear to work with components that are rendered only once.

**Comment by ChanhyukPark-Tech** [comment]
Oh. Thank you for finding error

Using `useState` instead of `useRef` is the correct approach. Because `useRef` is always used to maintain the same value even if a component is re-rendered, it may not be handled properly depending on the state change.
 
```tsx
import { useState } from "react";
import { useOutsideClickEffect } from "@toss/react";

export default function App() {
  const [wrapperEl, setWrapperEl] = useState(null);

  useOutsideClickEffect(wrapperEl, () => {
    console.log("outer");
  });

  return (
    <div className="App">
      <div
        ref={setWrapperEl}
        style={{ backgroundColor: "blue", width: 300, height: 300 }}
      ></div>

      <br />
      <button>OUTER Click</button>
    </div>
  );
}
```

**Comment by sa02045** [comment]
Thank you. I understand.
It would be nice if the changed usage is written in the document.

**Comment by sa02045** [comment]
The issue is resolved and the issue is closed.
