### ISSUE TITLE
[Feature]: common > utils > clamp error case

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toss/slash#34]
### **Package Scope**

- [x] Add to an existing package
- [ ] New package

Package name: @toss/utils

### **Overview**

In `clamp.ts`

Currently, the function is only supposed to work if bound1 is less than bound2. If user unaware of this rule and can put a larger value in bound1 than bound2. In that case, this function will not function normally. For example, if value=3, bound1=10, bound2=1, the return value must be 3, but the error results in 1.

### **Describe the solution you'd like**
i think this code works well if you agree I will make Pull request

```
export function clamp(value: number, bound1: number, bound2?: number) {
  if (bound2 == null) {
    return Math.min(value, bound1);
  }

  if (bound1 > bound2) {
    return Math.min(Math.max(value, bound2), bound1);
  }

  return Math.min(Math.max(value, bound1), bound2);
}
```

**Comment by raon0211** [comment]
I guess this is in fact a bug. However, I think throwing an error early when our assumption (`bound1 <= bound2`) is broken might be a better approach. (I think no one intends to write code like `clamp(3, 10, 1)` 😄 ) What do you think?

**Comment by ChanhyukPark-Tech** [comment]
Thank you for your kind answer.
This issue should have been a bug as you said, not a feature!

I think it would be better to throw an error than to give a wrong value.

I agree that no one will use it with `clamps (3, 10, 1)!`
However, the slash library is targeting a lot of users and it's getting bigger, so I think many users will use it. I think error handling is necessary because I can't be sure that it doesn't cause human errors as many users use it!

**Comment by raon0211** [comment]
Yes, so I guess we should change the implementation of clamp to throw an early error.

```typescript
function clamp(value, min, max) {
  if (min > max) {
    throw new Error("min is bigger than max");
  }

  // original implementation
}

**Comment by ChanhyukPark-Tech** [comment]
Yes! I agree🙋🏼‍♂️
If you allow me, I will make a PR after modifying it!
Will it be okay?

**Comment by raon0211** [comment]
Yes, sure!
