### ISSUE TITLE
[BUG]: arrayIncludes 유틸 함수 테스트 코드 타입 관련 이슈

### ISSUE THREAD

**Issue by ghdtjgus76** [toss/slash#416]
### **Package Scope**

Package name: @toss/utils

### **Describe the bug**
![image](https://github.com/toss/slash/assets/81316050/62012eff-c6de-4dbd-8119-75f569cf3ad7)
@toss/utils 라이브러리의 arrayIncludes 유틸 함수는 넓은 타입으로 인식되는 변수가 배열에 보다 좁은 타입으로 지정된 요소들 중 존재하는지 판단하는 여부를 반환하는 함수입니다.

하지만 테스트 코드를 보면, 아래와 같이 작성되어 있습니다.
아래와 같이 includedElement와 excludedElement의 경우 let이 아닌 const 키워드로 선언되었기 때문에 해당 변수의 타입이 각각 문자열 리터럴 타입인 'a'와 'd'로 인식됩니다.
```
it('should work identical to Array.prototype.includes', () => {
    const arr: Array<'a' | 'b' | 'c'> = ['a', 'b', 'c'];

    const includedElement = 'a';
    expect(arrayIncludes(arr, includedElement)).toBe(true);

    const excludedElement = 'd';
    expect(arrayIncludes(arr, excludedElement)).toBe(false);
  });
```

### **Expected behavior**

이 함수의 취지에 맞는 테스트 코드를 작성하기 위해서는 includedElement와 excludedElement 변수가 각각 string 타입으로 인식되도록 선언되어야 합니다.

### **Possible Solution**
따라서 이 함수의 취지에 맞는 방식은 아래 두 방식 중 하나인 것으로 예상됩니다.
1. const 대신 let 키워드를 사용해 선언
```
it('should work identical to Array.prototype.includes', () => {
    const arr: Array<'a' | 'b' | 'c'> = ['a', 'b', 'c'];

    let includedElement = 'a';
    expect(arrayIncludes(arr, includedElement)).toBe(true);

    let excludedElement = 'd';
    expect(arrayIncludes(arr, excludedElement)).toBe(false);
  });
```
2. string으로 타입 선언
```
it('should work identical to Array.prototype.includes', () => {
    const arr: Array<'a' | 'b' | 'c'> = ['a', 'b', 'c'];

    const includedElement: string = 'a';
    expect(arrayIncludes(arr, includedElement)).toBe(true);

    const excludedElement: string = 'd';
    expect(arrayIncludes(arr, excludedElement)).toBe(false);
  });
```

감사합니다.

**Comment by okinawaa** [comment]
thanks for reporting 😄
