### ISSUE TITLE
[BUG]: createTypedLocalStorage type inference fails with type boolean

### ISSUE THREAD

**Issue by injoonH** [toss/slash#428]
### **Package Scope**

Package name: `@toss/storage@1.3.1`

### **Describe the bug**

1. `createTypedLocalStorage<boolean>` returns `TypedStorage<false> | TypedStorage<true>`.
2. Its `set` method has type `(next: never) => void`.

### **Expected behavior**

1. `createTypedLocalStorage<boolean>` returns `TypedStorage<boolean>`.
2. Its `set` method has type `(next: boolean) => void`.

### **To Reproduce**

[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoE8AOEAmBlMAeyjgHMIB5TMYQkAZwB5UA+ZAbwChkfl6iS5APwAuZAWJkIAbm69QwGnAA2ANRUBXCKLSyAvpxwQEyuFBQm49emiy4JgiMzZdeyTFGAA3OJGQBrCHRZNw9vXxR+SXIQ3gQ6figNBAEACkD0MUTQUgAaZEJqWgYdDGx8ASkqGgTnAEpYnnIwVLqxVGQAH2QQDWVlRr4IFpAIAA8wdrbkL0JgHEGTCDNWsVn5wbCfP3poYBVgAC8ZOR4tiOQjXc8D4-1OQ2NTc2RLa2QAOQ0AWwAjaDK9kq5GQ40gIBwNkBFWiTl6f2gLlOyFACHMVggqUIMBguzAOnh-yg03WC2RRjRy12WJxeIJPyJJLmZIMj0sLzAdmQACUIPQ+mBnMgALxoUETCAQmyE6DIISfBkAuwwxzIdrKhxSZyyCnPFAwDQgFLFV7oyDQgAyhAQKk15Gc6SCWTAnhAeQKRQSOgo30UzA1wMonoYznyAHIoo4wyxprz+cpBawdU8zPrDca6KbluaNXz6MU7U5WI7MnwXTl8oUaiUxD6-dDC9VikxWOHI1Jo7G+QLtQ94gwwGXYSKsxFLdbbYHGL9CIRlMsQCxUgAidvkZf5VzyECKfZqTQQMTwZS7Th6BoPNcQAB0eNSLq0F84nOwyAAgiO4z2Z3OFyxpEAA)

```ts
import { createTypedLocalStorage } from "@toss/storage/typed";

const isSignedIn = createTypedLocalStorage<boolean>("isSignedIn", {
  initialValue: false,
});

isSignedIn.set(true);  // Argument of type 'boolean' is not assignable to parameter of type 'never'.
```

**Comment by okinawaa** [comment]
thank you for reporting 😀
