### ISSUE TITLE
[Question]:useOutsideClickEffect dependancies

### ISSUE THREAD

**Issue by tjrdnjs1534** [toss/slash#449]
### **Package Scope**

- [x] Add to an existing package
- [ ] New package

Package name: packages/react/react/src/hooks/useOutsideClickEffect.ts

### **Overview**

when useOutsideClickEffect, it will rerender everytime.
there is no dependacies on useOutsideClickEffect hook

### **Describe the solution you'd like**

when i use useOutsideClickEffect Hook, it should add eventListner once. and should remove it when component unmont.
i think 
```
  useEffect(() => {
    document.addEventListener('click', handleDocumentClick);
    document.addEventListener('touchstart', handleDocumentClick);

    return () => {
      document.removeEventListener('click', handleDocumentClick);
      document.removeEventListener('touchstart', handleDocumentClick);
    };
  });
```
to
```

  useEffect(() => {
    document.addEventListener('click', handleDocumentClick);
    document.addEventListener('touchstart', handleDocumentClick);

    return () => {
      document.removeEventListener('click', handleDocumentClick);
      document.removeEventListener('touchstart', handleDocumentClick);
    };
  }, []);
```
is there any reason there are no dependancies on this hook? 
im curious about it

**Comment by ssi02014** [comment]
I think that's a good catch!
However, `handleDocumentClick` should be added to the dependency array of the useEffect you fixed.
  - Why? `handleDocumentClick` function is memoized because it is written as a useCallback. 

Alternatively, I think you could use the `usePreservedCallback` custom hook! 
  - I've done something like the PR below, but it hasn't been reviewed yet, so take it as a guide.
  - https://github.com/toss/slash/pull/450

```tsx
export function useOutsideClickEffect(container: OneOrMore<HTMLElement | null>, callback: () => void) {
  const containers = useRef<HTMLElement[]>([]);

  useEffect(() => {
    containers.current = (Array.isArray(container) ? container : [container]).filter(isNotNil);
  }, [container]);

  const handleDocumentClick = usePreservedCallback(({ target }: MouseEvent | TouchEvent) => {
    if (target === null) {
      return;
    }

    if (containers.current.length === 0) {
      return;
    }

    if (containers.current.some(x => x.contains(target as Node))) {
      return;
    }

    callback();
  });

  useEffect(() => {
    document.addEventListener('click', handleDocumentClick);
    document.addEventListener('touchstart', handleDocumentClick);

    return () => {
      document.removeEventListener('click', handleDocumentClick);
      document.removeEventListener('touchstart', handleDocumentClick);
    };
  }, [handleDocumentClick]);
}
```
The test passes fine 👍
