### ISSUE TITLE
[Feature]: Hacktoberfest

### ISSUE THREAD

**Issue by anaclumos** [toss/slash#68]
- [Participation | Hacktoberfest 2022](https://hacktoberfest.com/participation/#pr-mr-details)

Would you mind registering @toss/slash as a Hacktoberfest participant?

> Your PR/MR was submitted to a repository not participating in Hacktoberfest. Maintainers need to add the <code>hacktoberfest</code> topic to the repository, or add the <code>hacktoberfest-accepted</code> label to your PR/MR.</p><p>For more information about how exactly we validate PR/MRs for contributors, check the <a href="https://hacktoberfest.com/participation/#pr-mr-details">details on our participation page</a>.</p></div>

**Comment by raon0211** [comment]
We have just added the `hacktoberfest` topic to our repository. Can you have a look?

**Comment by anaclumos** [comment]
Awesome! It is now working. Thank you for your help!

<img width="425" alt="image" src="https://user-images.githubusercontent.com/31657298/196806454-44397cd9-060a-4d9c-88b1-2284521dc74a.png">
