### ISSUE TITLE
[BUG]: `@toss/utils`의 `commaizeNumber` 함수 에러

### ISSUE THREAD

**Issue by ehgks0000** [toss/slash#71]
### **Package Scope** 
Package name: `@toss/utils` v1.0.4

### **Describe the bug**
![토스에러](https://user-images.githubusercontent.com/50390565/196907725-98a05409-0766-4406-9499-93ba586709bd.png)

16자리 수 넘는 순간부터 제대로 컴마가 찍히지 않는 것 같아요

### **Expected behavior**
```ts
console.log(commaizeNumber(1234123412341234)); // 1,234,123,412,341,234
console.log(commaizeNumber(12341234123412341)); // 12,341,234,123,412,341
console.log(commaizeNumber(123412341234123412)); // 123,412,341,234,123,412
console.log(commaizeNumber(1234123412341234123)); // 1,234,123,412,341,234,123
console.log(commaizeNumber(12341234123412341234)); // 12,341,234,123,412,341,234
```

### **To Reproduce** 
1. install `@toss/utils`
2. Use `commaizeNumber`
3. Run

**Comment by ehgks0000** [comment]
찾고보니 `MAX_SAFE_INTEGER` 범위 넘어서 그런건가 보네요.

**Comment by HoseungJang** [comment]
@ehgks0000 I think this is not a bug. Such a big integer value that the system cannot process is of course to be managed as `string`.
So `commaizeNumber` accepts `string` as well as `number`. [The passed string value will be parsed by RegExp and then replaced.](https://github.com/toss/slash/blob/11c50d95e764cfe0db87327f4bc5afc1a54a418b/packages/common/utils/src/Numbers.ts#L153)
