### ISSUE TITLE
[BUG]: useless field in package.json

### ISSUE THREAD

**Issue by airman5573** [toss/slash#76]
### **Package Scope** 

Package name: all package

### **Describe the bug**

```json
{
  "name": "@toss/assert",
  "version": "1.0.4",
  "sideEffects": false,
  "exports": {
    ".": {
      "require": "./src/index.ts",
      "import": "./src/index.ts"
    },
    "./package.json": "./package.json"
  },
  "main": "src/index.ts",
  "scripts": {
  },
  "dependencies": {
    "@toss/utils": "workspace:^1.0.4"
  },
  "devDependencies": {
    "typescript": "4.8.3"
  },
  "publishConfig": {
    "access": "public",
    "exports": {
      ".": {
        "require": "./dist/index.js",
        "import": "./esm/index.mjs",
        "types": "./dist/index.d.ts"
      },
      "./package.json": "./package.json"
    },
    "import": "./esm/index.mjs", // here
    "main": "dist/index.js",
    "module": "./esm/index.mjs",
    "types": "dist/index.d.ts"
  },
  "gitHead": "..."
}
```

I think `"import": "./esm/index.mjs",` field is not official field, and not used in anywhere.  

I checked this in [node](https://github.com/nodejs/node/blob/3a4f9649304776db7a3a62ebbc0cb477c60c6355/doc/api/packages.md#nodejs-packagejson-field-definitions) and [npm](https://docs.npmjs.com/cli/v8/configuring-npm/package-json).  But I couldn't find any explanation about the field.  

It seems that even webpack and rollup are not using "import" field of package.json.  

What's the purpose of the "import" field ?  

Check please :D

**Comment by HoseungJang** [comment]
@raon0211

**Comment by airman5573** [comment]
May I make a pull request about this ?

**Comment by airman5573** [comment]
of course, how can I help you?

**Comment by raon0211** [comment]
We should remove all import fields in our package.json.

**Comment by airman5573** [comment]
OK :D
